import = [
  "~/.config/alacritty/themes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = {x=15, y=15}

[font]
size = 8.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[cursor]
style = {shape = "Beam", blinking = "On"}
